Meal-Tracking-App/Controllers/EntriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Meal_Tracking_App.Data;
using Meal_Tracking_App.Models;
using Meal_Tracking_App.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Meal_Tracking_App.Controllers
{
    [Authorize]
    public class EntriesController : Controller
    {

        private EntryDbContext context;

        private IAuthorizationService authorizationService;

        private UserManager<IdentityUser> userManager;

        public EntriesController(EntryDbContext dbContext, IAuthorizationService authorizationService, UserManager<IdentityUser> userManager) : base()
        {
            context = dbContext;
            this.authorizationService = authorizationService;
            this.userManager = userManager;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            var currentUserId = userManager.GetUserId(User);

            List<Entry> entries = context.Entries
                .Where(e => e.UserId == currentUserId)
                .OrderBy(e => e.Date)
                .ThenBy(e => e.Time.TimeOfDay)
                .ToList();
                

            return View(entries);
                //.ThenBy(e => DateTime.Parse(e.Time)));
        }

        public IActionResult Add()
        {
            AddEntryViewModel addEntryViewModel = new AddEntryViewModel();

            return View(addEntryViewModel);
        }

        [HttpPost]
        public IActionResult Add(AddEntryViewModel addEntryViewModel)
        {
            if (ModelState.IsValid)
            {
                var currentUserId = userManager.GetUserId(User);

                Entry newEntry = new Entry
                {
                    Date = addEntryViewModel.Date,
                    Time = addEntryViewModel.Time,
                    Type = addEntryViewModel.Type,
                    Description = addEntryViewModel.Description,
                    Feelings = addEntryViewModel.Feelings,
                    UserId = currentUserId
                };

                context.Entries.Add(newEntry);
                context.SaveChanges();

                return Redirect("/Entries");
            }

            return View(addEntryViewModel);

        }

        public IActionResult Delete()
        {
            var currentUserId = userManager.GetUserId(User);

            ViewBag.entries = context.Entries
                .Where(e => e.UserId == currentUserId)
                .OrderBy(e => e.Date)
                .ThenBy(e => e.Time.TimeOfDay)
                .ToList();

            return View();
        }

        [HttpPost]
        public IActionResult Delete(int[] entryIds)
        {
            foreach (int entryId in entryIds)
            {
                Entry entry = context.Entries.Find(entryId);

                context.Entries.Remove(entry);
            }

            context.SaveChanges();

            return Redirect("/Entries");
        }

        public IActionResult Detail(int id)
        {
            Entry entry = context.Entries.Single(e => e.Id == id);

            EntryDetailViewModel viewModel = new EntryDetailViewModel(entry);

            return View(viewModel);

        }

        public IActionResult Edit(int id)
        {
            Entry entry = context.Entries.Find(id);

            return View(entry);
        }

        [HttpPost]
        public IActionResult Edit(Entry entry)
        //public async Task<IActionResult> Edit(Entry entry)
        {
            if(ModelState.IsValid)
            {
                context.Entry(entry).State = EntityState.Modified;
                context.SaveChanges();

                return Redirect("/Entries/Detail/" + entry.Id);
                //return RedirectToAction("index", "Entries");
            }

            return View(entry);
        }
    }
}

Meal-Tracking-App/Controllers/RecipesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Meal_Tracking_App.Data;
using Meal_Tracking_App.Models;
using Meal_Tracking_App.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Meal_Tracking_App.Controllers
{
    [Authorize]
    public class RecipesController : Controller
    {

        private EntryDbContext context;

        private IAuthorizationService authorizationService;
        private UserManager<IdentityUser> userManager;

        public RecipesController(EntryDbContext dbContext, IAuthorizationService authorizationService, UserManager<IdentityUser> userManager) : base()
        {
            context = dbContext;
            this.authorizationService = authorizationService;
            this.userManager = userManager;
        }

        public IActionResult Index()
        {
            var currentUserId = userManager.GetUserId(User);

            List<Recipe> recipes = context.Recipes
                .Where(r => r.UserId == currentUserId)
                .OrderBy(r => r.Name)
                .ToList();

            return View(recipes);
        }

        public IActionResult Add()
        {
            AddRecipeViewModel addRecipeViewModel = new AddRecipeViewModel();

            return View(addRecipeViewModel);
        }

        [HttpPost]
        public IActionResult Add(AddRecipeViewModel addRecipeViewModel)
        {
            if (ModelState.IsValid)
            {
                var currentUserId = userManager.GetUserId(User);

                Recipe newRecipe = new Recipe
                {
                    Name = addRecipeViewModel.Name,
                    Description = addRecipeViewModel.Description,
                    Link = addRecipeViewModel.Link,
                    Image = addRecipeViewModel.Image,
                    UserId = currentUserId
                };

                context.Recipes.Add(newRecipe);
                context.SaveChanges();

                return Redirect("/Recipes");
            }

            return View(addRecipeViewModel);
        }

        public IActionResult Delete()
        {
            var currentUserId = userManager.GetUserId(User);

            ViewBag.recipes = context.Recipes
                .Where(r => r.UserId == currentUserId)
                .OrderBy(r => r.Name)
                .ToList();

            return View();
        }

        [HttpPost]
        public IActionResult Delete(int[] recipeIds)
        {
            foreach(int recipeId in recipeIds)
            {
                Recipe recipe = context.Recipes.Find(recipeId);
                context.Recipes.Remove(recipe);
            }

            context.SaveChanges();

            return Redirect("/Recipes");
        }

        public IActionResult Detail(int id)
        {
            Recipe recipe = context.Recipes.Single(e => e.Id == id);

            RecipeDetailViewModel viewModel = new RecipeDetailViewModel(recipe);

            return View(viewModel);
        }

        public IActionResult Edit(int id)
        {
            Recipe recipe = context.Recipes.Find(id);

            return View(recipe);
        }

        [HttpPost]
        public IActionResult Edit(Recipe recipe)
        {
            if(ModelState.IsValid)
            {
                context.Entry(recipe).State = EntityState.Modified;
                context.SaveChanges();

                return Redirect("/Recipes/Detail/" + recipe.Id);
            }

            return View(recipe);
        }
    }
}

Meal-Tracking-App/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Meal_Tracking_App.Data;
using Meal_Tracking_App.Models;
using Meal_Tracking_App.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Meal_Tracking_App.Controllers
{
    [Authorize]
    public class SearchController : Controller
    {
        private IAuthorizationService authorizationService;

        private UserManager<IdentityUser> userManager;

        private EntryDbContext context;

        public SearchController(EntryDbContext dbContext, IAuthorizationService authorizationService, UserManager<IdentityUser> userManager) : base()
        {
            context = dbContext;
            this.authorizationService = authorizationService;
            this.userManager = userManager;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Results(DateTime searchDate)
        {
            var currentUserId = userManager.GetUserId(User);

            List<Entry> entries = context.Entries
                .Where(e => e.UserId == currentUserId)
                .Where(e => e.Date == searchDate)
                .OrderBy(e => e.Time.TimeOfDay)
                .ToList();

            List<EntryDetailViewModel> displayEntries = new List<EntryDetailViewModel>();

            foreach (Entry entry in entries)
            {
                EntryDetailViewModel newDisplayEntry = new EntryDetailViewModel(entry);
                displayEntries.Add(newDisplayEntry);
            }

            ViewBag.title = "Entries for " + searchDate.ToShortDateString();
            ViewBag.entries = displayEntries;
            return View("Index");
        }

    }
}

Meal-Tracking-App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Feed Your Health</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Feed Your Health</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @*<li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Entries" asp-action="Index">All Entries</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Search" asp-action="Index">Search Entries</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Entries" asp-action="Add">Add Entry</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Recipes" asp-action="Index">Favorite Recipes</a>
                        </li>
                        
                        @*<li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Recipes" asp-action="Add">Add Recipe</a>
        </li>*@
                    </ul>
                    <div>
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Feed Your Health - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>